name: Build and deploy api

on:
  push:
    branches: [ "main", "develop", "feature/**" ]

    paths:
      - functions/**
      - .github/workflows/build-and-deploy-api.yml

jobs:
  build_and_test:
    name: Build & Test API
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: functions

    steps:
    - uses: actions/checkout@v3

    - name: Install NPM dependencies
      run: npm install

    - name: Build API
      run: npm run build

  deploy_to_test:
    name: Deploy to Test Environment
    needs: build_and_test
    # if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy
      run: |
        npm i -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_FUNCTIONS_TOKEN }} --only functions --project doinfine-test


    