name: Deploy Web App to Firebase

on:
  push:
    branches: [ "main", "develop"]

    paths:
      - web/**
      - .github/workflows/**
  
defaults:
  run:
    working-directory: web

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install --legacy-peer-deps
      - run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOIN_FINE }}'
          projectId: doin-fine
          entryPoint: web