name: Deploy Web App to Firebase

on:
  push:
    branches: [ "main", "develop", "feature/**", "bugfix/**" ]

    paths:
      - web/**
      - .github/workflows/deploy-web.yml

defaults:
  run:
    working-directory: web

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm install --legacy-peer-deps
      - run: npm run build
      - run: npm run test

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOIN_FINE }}'
          projectId: doin-fine
          entryPoint: web
          channelId: dev

  # preview:
  #   needs: build_and_test
  #   if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: FirebaseExtended/action-hosting-deploy@v0
  #       with:
  #         repoToken: '${{ secrets.GITHUB_TOKEN }}'
  #         firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOIN_FINE }}'
  #         projectId: doin-fine

  # deploy_to_dev: 
  #   needs: build_and_test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/develop'

  #   steps:
  #     - uses: FirebaseExtended/action-hosting-deploy@v0
  #       with:
  #         repoToken: '${{ secrets.GITHUB_TOKEN }}'
  #         firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOIN_FINE }}'
  #         projectId: doin-fine
  #         entryPoint: web
  #         channelId: dev

  # deploy_to_prod: 
  #   needs: build_and_test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - uses: FirebaseExtended/action-hosting-deploy@v0
  #       with:
  #         repoToken: '${{ secrets.GITHUB_TOKEN }}'
  #         firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOIN_FINE }}'
  #         projectId: doin-fine
  #         entryPoint: web
  #         channelId: live