# name: Deploy Web App To Firebase to Production

# on:
#   push:
#     branches: [ "main" ]

#     paths:
#       - web/**
#       - .github/workflows/deploy-web.yml
  
# defaults:
#   run:
#     working-directory: web

# jobs:
#   build_and_preview:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout out repo
#         uses: actions/checkout@v2

#       - name: Install NPM packages
#         run: npm install --legacy-peer-deps

#       - name: 'Create env file'
#         run: |
#           touch .env
#           echo DF_ENVIRONMENT=Production >> .env
#           cat .env
          
#       - name: Build
#         run: npm run build

#       - name: Test
#         run: npm run test

#       - name: Deploy to Firebase Hosting
#         uses: FirebaseExtended/action-hosting-deploy@v0
#         if: github.ref == 'refs/heads/main'
#         with:
#           repoToken: '${{ secrets.GITHUB_TOKEN }}'
#           firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DOIN_FINE }}'
#           projectId: doin-fine
#           entryPoint: web
#           channelId: live