name: Deploy Database

on: 
  push: 
    branches: ['develop']

jobs: 
  UpdateDatabase: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Install EF Tool
        run: |
            dotnet new tool-manifest
            dotnet tool install dotnet-ef
      
      - name: Update Database
        run: dotnet ef database update
        working-directory: api/TeamLunch