# variables: 
#   buildConfiguration: 'Release'

# steps: 
# - script: dotnet build --configuration $(buildConfiguration)
#   workingDirectory: api
#   displayName: 'dotnet build $(buildConfiguration)'

# - task: DotNetCoreCLI@2
#   inputs: 
#     command: 'publish'
#     publishWebProjects: true

# - task: AzureWebApp@1
#   inputs: 
#     azureSubscription: AzureSubscription1
#     appType: 'webAppLinux',
#     appName: 'dev-api-corporate-brewshack'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      working-directory: ./api
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./api
      run: dotnet restore
    - name: Build
      working-directory: ./api
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./api
      run: dotnet test --no-build --verbosity normal
