name: Build and deploy .NET API

on:
  push:
    branches: [ "main", "develop"]

    paths:
      - api/**

env:
  AZURE_WEBAPP_NAME: dev-api-team-lunch    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './api/TeamLunch'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use

defaults:
  run:
    working-directory: api

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - nam: Install ef core tools
      run: dotnet tool install --global dotnet-ef

    - name: Update Database
      run: dotnet ef database update

    - name: Publish
      run: dotnet publish -c Release -o build
      working-directory: api/TeamLunch

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/build'
